### ISSUE TITLE
Inference by the released checkpoint?

### ISSUE THREAD

**Issue by hjoh01** [BianChang/pix2pix#4]
Hello,

I've downloaded the checkpoint released in this repository and I'm trying to reproduce the results presented in your paper. However, I'm encountering some difficulties in getting the same output predictions.

I have a question regarding the input image preprocessing. Do you apply any additional preprocessing steps more than normalizing the pixel values to the range of [-1, 1]? 

Could you please provide more details on the exact preprocessing steps or any other considerations needed to accurately reproduce the outputs as shown in your paper?

Thank you for your help!

**Comment by BianChang** [comment]
Hi,

There are no additional preprocessing steps in this project beyond normalizing the pixel values to the range of [-1, 1], which matches the preprocessing used in our paper. The exact code used for this experiment, including preprocessing details, is available in the repository.

If you’re using the provided checkpoint for inference on the test set, it should yield similar results to those in the paper. However, please note that minor differences can sometimes occur due to factors like hardware or software version discrepancies.

Let me know if you have further questions!

**Comment by hjoh01** [comment]
Hi, thank you for your response!
I have run your checkpoint on the released code without any change, but I got the result as below. The figure consists of [prediction, H&E input, IHC gt]. Do I need to apply the color normalization on the input images?

<img width="2115" alt="Screenshot 2024-11-06 at 11 48 52 AM" src="https://github.com/user-attachments/assets/84a7ca70-0098-48a7-8777-754119ae4bee">

**Comment by BianChang** [comment]
Hi! I checked the issue and realized I had uploaded the wrong checkpoint, which was trained on a HER2 IHC dataset. I’ve updated the download link. It should generate reasonable outputs if you download it again and re-run it on the test set.

Thank you for spotting this, and apologise for the inconvenience!

Feel free to let me know if you have other questions!

**Comment by hjoh01** [comment]
Thank you for your response! 
Once you change the permissions for the newly updated checkpoint to make it available to everyone, it be possible for me to download it :)

**Comment by BianChang** [comment]
Fixed it, should work now!

**Comment by hjoh01** [comment]
Thank you!
